name: Build test KernelSU

on:
  workflow_dispatch:
  watch:
   types: [started]

defaults:
  run:
   shell: bash

jobs:
 buildtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with: 
          swap-size-gb: 5
         
      - name: setup package
        run: |
         ./S
         
      - name: cloning KernelSU
        run: |
         curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5

      - name: clean up
        run: |
         make clean; make mrproper

      - name: check clang version
        run: |
         clang -v
         
      - name: start up
        run: |
         ./build

      - name: anykernel ~ zipping
        run: |
         git clone https://github.com/Frostleaft07/AnyKernel3 -b KernelSU any/
         cp out/arch/arm64/boot/Image.gz-dtb any/
         cd any/ && zip -r9 KernelSU-${{ github.run_id }}.zip *
         
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
           files: |
            any/KernelSU*
           name: KernelSU-${{ github.run_id }}
           tag_name: ${{ github.run_id }}
        env:
         GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
